### ISSUE TITLE
no model

### ISSUE THREAD

**Issue by JISHNU04** [cryptonymous9/CARO-An-Empathetic-chatbot#1]
where is training code and model saving code can't find here

**Comment by cryptonymous9** [comment]
Hi Jishnu,
- This project is a web-demo of CARO, therefore, it doesn't include the training code.
-  However, you can find the model configuration of each of the subnetwork showed in the pipeline in the following path:
`Model_files/[network_name]/[network_name]_model.json` in JSON Format.
- You can load model these models in `Tensorflow`. For this refer [here](https://www.tensorflow.org/api_docs/python/tf/keras/models/model_from_json). 
- Also, I'll soon be providing an external link for all the pre-trained weights of these subnetworks. 

Thanks,
