### ISSUE TITLE
weight is needed

### ISSUE THREAD

**Issue by JISHNU04** [cryptonymous9/CARO-An-Empathetic-chatbot#2]
****weight** is needed for the working of the full chatbot
how can i get it?**__

**Comment by cryptonymous9** [comment]
Hi Jishnu,
I did mention that in my previous reply. Please read the fourth point [here](https://github.com/cryptonymous9/CARO-An-Empathetic-chatbot/issues/1#issuecomment-655386294).
Thanks,

**Comment by JISHNU04** [comment]
Sir ,
I notice the point
If u have time please provide that externl link
Because i am a final year mca student and my project topic is also this
chatbot
And my project review is just bit far
If u don't mind please give that external link mention in the thread today
or tomorrow
It will be very helpful and thankfull
I tried to contact in several ways but can't get u 
Please understand my situation
